### ISSUE TITLE
Event Creation Size

### ISSUE THREAD

**Issue by marcoelho97** [firemankurt/MyCalendar#10]
Hello, I want to thank you for the recurring!! It's so handy! Thank you very much!!
It only has 1 issue now. Nothing BIG, and not that bad, but, I think it could be easily fixed.

When creating an Event, Daily, the Selects get REALLY small, shortening what one can see.
See here: http://prntscr.com/b2cduq

**Comment by marcoelho97** [comment]
Also, there's an error at:
"Event details
Enter detailed decsription of the event. ( HTML OK )."
description*

Once again, thank you very much! :)

**Comment by marcoelho97** [comment]
Oh, one more thing: ListEvents Component Link Pages are not showing D:
It's probably due to the include you do from "Events" component D:

**Comment by firemankurt** [comment]
I think these issues have been fixed.
