### ISSUE TITLE
Translate Plugin with Event creation

### ISSUE THREAD

**Issue by marcoelho97** [firemankurt/MyCalendar#12]
Hello,

I just noticed a bug with the last version:
If you use RainLab's translation plugin implement, it won't work! The EN will show up in both title and details ( I chose those 2 fields ), but, when I click it, nothing happens.

I have updated to this new version, and I'm having trouble with it, hope you can help me out!!

**Comment by firemankurt** [comment]
Translate plugin not currently supported by this plugin.  This plugin uses lan.php files to provide translation via normal October CMS methods.
There are currently 3 languages.

**Comment by marcoelho97** [comment]
Oh, well, it used to be, because I used to implement Rainlab.Translate.
Would there be a chance to fix it in order to be able to use this again? It is a very important feature, in my opinion.

Best regards,
Marco Coelho
