### ISSUE TITLE
Recuring Event Pattern property not updating

### ISSUE THREAD

**Issue by sasokovacic** [firemankurt/MyCalendar#16]
Hi, 
"Repeat - None (run once)" option is not stored when I create new or update existing event. When I open any event for editing it selects "Daily" option. Please fix this bug asap if you can... I'm currently working on a project that will need this functionality....

**Comment by firemankurt** [comment]
Every entry creates a recurrence rule. ( RRULE ) per iCalendar Specifications 
See: http://www.kanzaki.com/docs/ical/rrule.html

When you select "None" for recurrence, It is actually creating the RRULE:

"FREQ=DAILY;INTERVAL=1;COUNT=1;" 

Which is the same a no repeat.  The "None" option was added to the form as a convenience but when it is parsed by the script back into pieces for the form it is represented by the more complex DAILY option.

**Comment by sasokovacic** [comment]
I get it now... thanks for the explanation...
