### ISSUE TITLE
Class 'Recurr\Rule' not found

### ISSUE THREAD

**Issue by rangrage** [firemankurt/MyCalendar#25]
Hi Kurt,

I am having the following error when trying to add an event. 

"Class 'Recurr\Rule' not found" on line 298 of ~PATH\plugins\kurtjensen\mycalendar\models\Event.php"

This is on a new installation and the CMS and plugins are up to date. 

Can you please have a look at this for me? 

Kind Regards. 
Riyaz

**Comment by firemankurt** [comment]
Looks like failed installation.  Composer did not install dependency.
