### ISSUE TITLE
Invalid datetime format on create new event

### ISSUE THREAD

**Issue by JumpLink** [firemankurt/MyCalendar#27]
I can't publish any event and get this error messages:
```mysql
"SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2038-03-09 17:00:00' for column 'start_at' at row 1 (SQL: insert into `kurtjensen_mycalendar_occurrences` (`event_id`, `relation`, `relation_id`, `start_at`, `end_at`, `is_allday`, `updated_at`, `created_at`) values (4, events, 4, 2038-03-09 17:00:00, 2038-03-10 11:00:00, 0, 2017-08-14 20:43:22, 2017-08-14 20:43:22))" on line 666 of /srv/users/freifunk/apps/freifunk-cuxhaven/public/vendor/laravel/framework/src/Illuminate/Database/Connection.php
```

![auswahl_752](https://user-images.githubusercontent.com/1073989/29290995-600acdca-8142-11e7-8016-a5160a48caf8.png)

My Timezone is `(UTC +02:00) Europe/Berlin`:

![auswahl_753](https://user-images.githubusercontent.com/1073989/29291050-98f1fb90-8142-11e7-8faf-b5d9cc2d9c34.png)

**Edit**
Seems to get this working with a dirty workaround by select `Every 2 month(s)` press save and then select `Every 1 month(s)` and press save again, if I don't do thisI can't save and the the error message:

![auswahl_754](https://user-images.githubusercontent.com/1073989/29291501-184f1750-8144-11e7-856c-de4fae789e5f.png)

**Comment by firemankurt** [comment]
Can you try entering your event "Date" as "2017-10-18" or "10-18-2017" to see if error still appears?

Not familiar with your customary date format but using DD.MM.YYYY seems to be confusing date string converter and Database.
