### ISSUE TITLE
Calendar icon don't print correct month

### ISSUE THREAD

**Issue by Seykhel** [firemankurt/MyCalendar#3]
Hi, when i add new event in next moth the calendar icon show current  month with correct day.
Thank you

<img width="825" alt="screenshot" src="https://cloud.githubusercontent.com/assets/8466042/11794347/23a9f098-a2b1-11e5-9696-4c57768ea2e2.png">

**Comment by firemankurt** [comment]
See edited example here: https://octobercms.com/plugin/kurtjensen-mycalendar/all-events#post-10444
for new way to display month heading using:
    <div class="month {{ MyM.color }}">
        <p>{{ (m~'/1/'~y)|date('M') }}</p>
    </div>
for month heading.
