### ISSUE TITLE
Could we use this as a base for a church calendar plugin? It will also be free.

### ISSUE THREAD

**Issue by pastorryanhayden** [firemankurt/MyCalendar#6]
Kurt,
Would you mind if we use what you've done here as a base for a church calendar plugin we are working on?  I know it's allowed by the license.  It will also be free.  
We were working on creating one from scratch when we saw this.  Figured it might save us some time.  We will definitely credit you.

**Comment by firemankurt** [comment]
Feel free to extend it and use it.  There are several ways you can do this without recreating the plugin.
For example:

Take a look at https://github.com/firemankurt/MyCalendar/blob/master/components/MonthEvents.php

Or you can just inject data into page with your own component:
        $this->page['myevents'] = [
            2016 => [
                2 => [
                    15 => [
                        [
                            'name' => 'February Potluck',
                            'date' => 'February 15',
                            'time' => '1pm',
                            'text' => 'Come get some great food and socialize.',
                        ],
                    ],
                ],
            ],
        ];
and use the month component to display it like this:
{% component 'Month' events = myevents %}

What other features do you need?  You may be able to extend the Event model to add extra fields if you want to store other data.  

Let me know what features you are looking to add and maybe we can add them to the current plugin.
I am just starting to integrate the calendar into another plugin that I am working on so I am constantly looking for ways to improve the plugin and make it easier to extend.  If I have a good understanding of what you are trying to accomplish I may be able to help you save even more time.
Kurt Jensen

**Comment by Codenator81** [comment]
@firemankurt We need in event model excerpt, multidate (repeater with multi data), excluded (repeater with multi data), allday (boolean), thru , recur (Recuring)
