### ISSUE TITLE
Bug when updating

### ISSUE THREAD

**Issue by marcoelho97** [firemankurt/MyCalendar#8]
So, I have a Test October installation. In that installation, I have been updating "MyCalendar" every now and then. I'm at the current version ( 1.1.12 ), all working well ( Good job, by the way ;D ). But, when I installed it at an "In Production Site", from version 1.0.18 to 1.1.12, it gives me this error when entering CMS: http://prntscr.com/ai0n9t
So, I can no longer enter the CMS.....
Hope you can fix it.

Kindest regards,
Marco Coelho

**Comment by marcoelho97** [comment]
Also, it's not ordering the events.. http://prnt.sc/ai29dh They are going at random, it seems... Is it fixable?

**Comment by marcoelho97** [comment]
Add this to "\components\Events.php" Line 142
        orderBy('start_at', 'ASC')->

That fixed for me ;D

**Comment by firemankurt** [comment]
1.1.13: Fixes error caused by removal of test component. Adds sorting.

**Comment by firemankurt** [comment]
Thanks for letting me know about these issues.
