### ISSUE TITLE
Missing argument 1

### ISSUE THREAD

**Issue by Twiebie** [firemankurt/MyCalendar#9]
Hi,

Just did a fresh install of MyCalendar but unfortunately it throws an error trying to save an event:

```Missing argument 1 for KurtJensen\MyCalendar\Controllers\Events::create_onSave()```

The post data is empty:

```
:
undefined:
```

Is it actually correct to pass $id to create_OnSave()?

**Comment by firemankurt** [comment]
Fixed:

1.1.18: Located and eliminated bastard div end tag that screwed up backend
form.

Sorry for your troubles.
